#!/bin/bash

#
# Checker wrapper script
#
# 2008-2009, Mircea Bardac, dev@mircea.bardac.net
# 2012, Razvan Deaconescu, razvan.deaconescu@cs.pub.ro
#

tests_dir="tests"
config_file="./config"
log_base="/tmp/rl-checker-$(date +%F-%T)"

test_max_array=(1 7 5 3 3 5 3 5 8 8 8 9 11 9 9 7 7 7 7)
test_inside_max_array=(1 8 6 2 16 3 3 2 5 10 12 1 2 1 3 6 16 1 4)
test_result_array=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)

function exec_test() {
    test_name="$1"
    id=$(echo "$test_name" | sed 's/.*\([0-9][0-9]\)/\1/' | awk '{printf "%d", $1;}')
    export log_file="$log_base/$(basename $test_name).log"
    bash -c "source $config_file; source $(pwd)/$test_name"
    ret=$?
    test_result_array[$id]=$(echo "" | awk "{printf \"%4.2f\", $ret * ${test_max_array[$id]} / ${test_inside_max_array[$id]}}")
    echo "" | awk "{printf \"%-20s ...............  %4.2f/%4.2f\n\", \"$test_name\", ${test_result_array[$id]}, ${test_max_array[$id]}}"
}

if test $UID != 0; then
    echo "Error: check trebuie executat ca 'root'."
    exit 1
fi

mkdir "$log_base" > /dev/null 2>&1

if test $# -eq 1; then
    p=$1
    test $1 -lt 10 && p="0$p"
    if test ! -f "$tests_dir/test_$p"; then
        echo "Test number $p does not exist."
        exit 1
    fi
    exec_test "$tests_dir/test_$p"
    exit 0
fi

list=$(find $tests_dir/ -regex "$tests_dir/test_[0-9][0-9]" | sort)
#list=$(find $tests_dir/ -name "test_*" | sort)
for t in $list; do
    exec_test "$t"
done

total=$(for i in $(seq 1 18); do
    echo ${test_result_array[$i]};
done | awk '
BEGIN {
    sum=0;
}

{
    sum += $1;
}

END {
    printf "%5.2f", sum;
}')

printf "\n%-20s ............... %5s/100.00\n" "Total" "$total"
