#!/bin/bash

#
# Checker configuration file. Consists of functions, variables etc.
#

function noout()
{
	 > /dev/null 2>&1 $@
}

function log()
{
	>> "$log_file" 2>&1 $@
}

ipv4_is_connected()
{
	ping -c 1 $1
}

ipv6_is_connected()
{
	ping6 -c 1 $1
}

run_ct()
{
	host="$1"
	shift
	command="$*"
	llxc.py exec "$host" '"'"$command"'"'
}
