#!/bin/bash

#
# Checker configuration file. Consists of functions, variables etc.
# Current directory is set to the home dir of the user executing check.
#

username=$(cat /root/info 2> /dev/null)

function notify()
{
	echo -e "  - Notification: $@" >> $output_file
}

function warn()
{
	echo -e "  - Warning: $@" >> $output_file
}

function err()
{
	echo -e "\e[0;31m  - Error: $@\e[m" >> $output_file
}

function noout()
{
	 > /dev/null 2>&1 $@
}

function log()
{
	 >> "$log_file" 2>&1 $@
}

function check_return()
{
	if test $? -ne 0; then
		[ $# -eq 2 ] && err "[$1] $2"
		[ $# -eq 1 ] && err "$1"
		return 1
	fi
	return 0
}

function vzexec()
{
	veid="$1"; shift; cmd="$@"
	#echo "$cmd" | vzctl exec2 "$veid" -
}


function vzpath()
{
	echo /var/lib/vz/private/$1
}

function exit_test()
{
	type test_cleanup 2>&1 | grep 'is a function' &>/dev/null
	[ $? -eq 0 ] && test_cleanup
	exit $1
}

function vz_check_port()
{
	veid=$1
	port=$2

	#vzexec $veid "netstat -tlpn | tail -n +3 | awk -F '[ \t]+' '{print \$4;}' | sed 's/.*:\([0-9]\+\)$/\1/' | grep $port"
}

function check_file()
{
	file=$1

	test -f $file
}

function vz_check_file()
{
	veid=$1
	vzfile=$(vzpath $veid)/$2

	test -f $file
}

function check_file_type()
{
	file=$1
	type="$2"

	file $file | grep "$type"
}


function vz_check_file_type()
{
	veid=$1
	file=$(vzpath $veid)/$2
	type="$3"

	file $file | grep "$type"
}

function vz_copy_to()
{
	veid=$1
	src=$2
	dst=$(vzpath $veid)/$3

	cp -r $src $dst
}

function vz_copy_from()
{
	veid=$1
	src=$(vzpath $veid)/$2
	dst=$3

	cp -r $src $dst
}

function vz_copy_from_to()
{
	veid_src=$1
	veid_dst=$2
	src=$(vzpath $veid_src)/$3
	dst=$(vzpath $veid_dst)/$4

	cp -r $src $dst
}

function vz_diff_to()
{
	veid=$1
	src=$2
	dst=$(vzpath $veid)/$3

	diff -r $src $dst
}

function vz_diff_from()
{
	veid=$1
	src=$(vzpath $veid)/$2
	dst=$3

	diff -r $src $dst
}

function vz_diff_from_to()
{
	veid_src=$1
	veid_dst=$2
	src=$(vzpath $veid_src)/$3
	dst=$(vzpath $veid_dst)/$4

	diff -r $src $dst
}

function get_iface()
{
	/sbin/route -n | grep '^0\.0\.0\.0' | awk -F '[ \t]+' '{print $8;}'
}

function get_ip()
{
	iface=$(get_iface)
	ifconfig $iface | grep 'inet addr' | awk -F '[ :\t]+' '{print $4;}'
}

function vz_get_iface()
{
	veid=$1
	echo "eth0"
}

function vz_get_ip()
{
	veid=$1
	iface=$(vz_get_iface $veid)
	#vzexec $veid "ifconfig $iface | grep 'inet addr' | awk -F '[ :\t]+' '{print \$4;}'"
}

function get_random_string()
{
	len=$1

	tr -d -c A-Za-z0-9 < /dev/urandom | head -c $len
}


ipv4_is_connected()
{
	ping -c 1 $1
}

ipv6_is_connected()
{
	ping6 -c 1 $1
}

run_ct()
{
	host=$1
	shift
	command=$@
	ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no -l root "$host" "$command"
}

cd /root
