#!/bin/bash

run_ct red ping -c 1 5.5.5.1 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 0
run_ct blue ping -c 1 5.5.5.2 2>&1 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 1

exit 2
