#!/bin/bash

ip=$(ping -c 1 host 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "1.1.1.1-" || exit 0

ip=$(ping -c 1 red 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "1.1.1.2-" || exit 1

ip=$(ping -c 1 green 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "2.2.2.2-" || exit 2

ip=$(ping -c 1 blue 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "3.3.3.2-" || exit 3

ip=$(run_ct red ping -c 1 host 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "1.1.1.1-" || exit 4

ip=$(run_ct red ping -c 1 red 2> /dev/null| tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "1.1.1.2-" || exit 5

ip=$(run_ct red ping -c 1 green 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "2.2.2.2-" || exit 6

ip=$(run_ct red ping -c 1 blue 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "3.3.3.2-" || exit 7

ip=$(run_ct green ping -c 1 host 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "2.2.2.1-" || exit 8

ip=$(run_ct green ping -c 1 red 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "1.1.1.2-" || exit 9

ip=$(run_ct green ping -c 1 green 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "2.2.2.2-" || exit 10

ip=$(run_ct green ping -c 1 blue 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "3.3.3.2-" || exit 11

ip=$(run_ct blue ping -c 1 host 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "3.3.3.1-" || exit 12

ip=$(run_ct blue ping -c 1 red 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "1.1.1.2-" || exit 13

ip=$(run_ct blue ping -c 1 green 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "2.2.2.2-" || exit 14

ip=$(run_ct blue ping -c 1 blue 2> /dev/null | tee -a $log_file | head -1 | awk -F '[ ()]+' '{print $3;}')
test $? -eq 0 -a "$ip-" == "3.3.3.2-" || exit 15

exit 16
