#!/bin/bash

run_ct red /root/scripts/get-host-ports | tee -a $log_file > /tmp/out
grep -w 'smtp' /tmp/out | grep -w 'Postfix' > /dev/null 2>&1 || exit 0
grep -w 'http' /tmp/out | grep -w 'Apache' > /dev/null 2>&1 || exit 1
grep -w 'imap' /tmp/out | grep -w 'Courier' > /dev/null 2>&1 || exit 2

log /etc/init.d/apache2 stop
run_ct red /root/scripts/get-host-ports 2>&1 | tee -a $log_file > /tmp/out
grep -w 'http' /tmp/out | grep -w 'Apache' && exit 3
log /etc/init.d/apache2 start

rm /tmp/out

exit 4
