#!/bin/bash

log ipv4_is_connected 1.1.1.2 || exit 0
log ipv4_is_connected 2.2.2.2 || exit 1
log ipv4_is_connected 3.3.3.2 || exit 2

log run_ct red ping -c 1 1.1.1.1 || exit 3
log run_ct green ping -c 1 2.2.2.1 || exit 4
log run_ct blue ping -c 1 3.3.3.1 || exit 5
log run_ct red ping -c 1 4.4.4.1 || exit 6
log run_ct blue ping -c 1 4.4.4.2 || exit 7

exit 8
