#!/bin/bash

run_ct red nc -w 2 host 50222 | tee -a $log_file | grep 'SSH' > /dev/null 2>&1 || exit 0
run_ct red nc -w 2 host 50322 | tee -a $log_file | grep 'SSH' > /dev/null 2>&1 || exit 1
run_ct green nc -w 2 host 50122 | tee -a $log_file | grep 'SSH' > /dev/null 2>&1 || exit 2
run_ct green nc -w 2 host 50121 | tee -a $log_file | grep 'vsFTPd' > /dev/null 2>&1 || exit 3
run_ct red nc -w 2 host 50269 > /dev/null 2>&1 || exit 4

exit 5
