#!/bin/bash

log rm -fr /var/www/answers/*
log mkdir -p /var/www/answers
log rm -fr /tmp/task-11/*
log mkdir -p /tmp/task-11

for i in $(seq 0 9); do
    log cp tpl/auth-message-template.php /var/www/answers/$i.php
    word=$(< /dev/urandom tr -d -c 'a-z' | head -c 20)
    echo "$word" >> /tmp/task-11/expected.txt
    sed -i "s/MESSAGE_TEMPLATE/$word/g" /var/www/answers/$i.php
done

log run_ct red rm -fr /tmp/task-11/*
log run_ct red mkdir -p /tmp/task-11/

run_ct red 'cd /tmp/task-11/ ; /root/scripts/www-get-messages > /tmp/task-11/actual.txt' >> $log_file 2> /dev/null

log diff -B /tmp/task-11/expected.txt /var/lib/lxc/red/rootfs/tmp/task-11/actual.txt || exit 0

exit 1
