#!/bin/bash

run_ct green nc -w 2 host 25 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 || exit 0
run_ct red nc -w 2 host 25 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 1
run_ct green nc -w 2 host 143 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 || exit 2
run_ct red nc -w 2 host 143 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 3
run_ct green nc -w 2 host 993 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 || exit 4
run_ct red nc -w 2 host 993 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 5
run_ct blue nc -w 2 red 21 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 || exit 6
run_ct green nc -w 2 red 21 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 7
run_ct red nc -w 2 green 6969 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 || exit 8
run_ct blue nc -w 2 green 6969 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 9

exit 10
