#!/bin/bash

log run_ct red ping -c 1 2.2.2.2 || exit 0
log run_ct red ping -c 1 3.3.3.2 || exit 1
log run_ct green ping -c 1 1.1.1.2 || exit 2
log run_ct green ping -c 1 3.3.3.2 || exit 3
log run_ct blue ping -c 1 1.1.1.2 || exit 4
log run_ct blue ping -c 1 2.2.2.2 || exit 5

exit 6
