#!/bin/bash

run_ct red /root/scripts/get-host-ports | tee -a $log_file > /tmp/out
grep -w 'smtp' /tmp/out | grep -w 'Postfix' > /dev/null 2>&1 || exit 0
grep -w 'http' /tmp/out | grep -w 'Apache' > /dev/null 2>&1 || exit 1
grep -w 'rpcbind' /tmp/out > /dev/null 2>&1 > /dev/null 2>&1 || exit 2
grep -w 'imap' /tmp/out | grep -w 'Courier' > /dev/null 2>&1 || exit 3
grep -w 'ssl/imap' /tmp/out | grep -w 'Courier' > /dev/null 2>&1 || exit 4

log /etc/init.d/apache2 stop
run_ct red /root/scripts/get-host-ports | tee -a $log_file > /tmp/out
grep -w 'http' /tmp/out | grep -w 'Apache' && exit 5
log /etc/init.d/apache2 start

rm /tmp/out

exit 6
