#!/bin/bash

run_ct 1.1.1.2 ping -c 1 2.2.2.2 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 0
run_ct 1.1.1.2 ping -c 1 3.3.3.2 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 1
run_ct 2.2.2.2 ping -c 1 1.1.1.2 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 2
run_ct 2.2.2.2 ping -c 1 3.3.3.2 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 3
run_ct 3.3.3.2 ping -c 1 1.1.1.2 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 4
run_ct 3.3.3.2 ping -c 1 2.2.2.2 2>&1 | tee -a $log_file | grep 'warning:' > /dev/null 2>&1 && exit 5

exit 6
