#!/bin/bash

run_ct red host -W 3 google.com 2>&1 | grep 'warning:' > /dev/null 2>&1 && exit 0
run_ct green host -W 3 google.com 2>&1 | grep 'warning:' > /dev/null 2>&1 && exit 1
run_ct blue host -W 3 google.com 2>&1 | grep 'warning:' > /dev/null 2>&1 && exit 2

exit 3
